---
abstract: 'Pretending to be Acme::CPAN::Testers::UNKNOWN'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPAN-Testers-UNKNOWN
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Acme::CPAN::Testers::FalsePositive:
    file: lib/Acme/CPAN/Testers/FalsePositive.pm
    version: 0.03
requires:
  perl: 5.008001
  strict: 0
  warnings: 0
version: 0.03
