---
abstract: 'generate an UNKNOWN test report'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPAN-Testers-UNKNOWN
no_index:
  directory:
    - inc
    - t
provides:
  Acme::CPAN::Testers::UNKNOWN:
    file: lib/Acme/CPAN/Testers/UNKNOWN.pm
    version: 0.02
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
